# Ulaş Can Demirbağ
# 20200702119

all: hw1a hw1b hw1c hw1d

hw1a: hw1a.c
	gcc -o hw1a.out hw1a.c

hw1b: hw1b.c
	gcc -o hw1b.out hw1b.c -lpthread

hw1c: hw1c.c
	gcc -o hw1c.out hw1c.c -lpthread

hw1d: hw1d.c
	gcc -o hw1d.out hw1d.c

run: 
	bash index.sh

clean:
	rm -f hw1a.out hw1b.out hw1c.out hw1d.out
